# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Jobs: Are collections of steps. 
jobs: 
  build: 
    working_directory: ~/circleci-python
    docker: 
      - image: "circleci/python:3.6.4"
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    steps: 
      - checkout
      - run: python3 main.py
      - run: echo $CIRCLE_COMPARE_URL
  test:
    working_directory: ~/circleci-python
    docker: 
      - image: "circleci/python:3.6.4"
    steps: 
      - checkout
      - run: python3 main-test.py
  build-on-production: 
    working_directory: ~/circleci-python
    docker: 
      - image: "circleci/python:3.6.4"
    steps: 
      - checkout
      - run: python3 main.py
    cancel-other-hold:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - run:
          name: Cancelling the other on_hold workflow
          command: |
            other_id=$(curl -s -X GET 'https://circleci.com/api/v2/project/gh/VeroMunoz/pipeline-ci-cd/pipeline?circle-token=${TOKEN}' | jq -r --arg CIRCLE_USERNAME "$CIRCLE_USERNAME" '.items[]|select(.state == "created").id')
            echo $other_id  
            for other_id in $other_id
              do
                workflow_id=$(curl -s -X GET "https://circleci.com/api/v2/pipeline/${other_id}/workflow" | jq -r '.items[]|select(.status == "on_hold").id')
                curl -s --header "Circle-Token: $PERSONAL_TOKEN" -X POST https://circleci.com/api/v2/workflow/${workflow_id}/cancel
              done  

workflows: 
  build_and_test: 
    jobs: 
      - build
      - test: 
          requires:
            - build
      - hold: 
          type: approval
          requires: 
           - test
      - build-on-production:
          requires:
            - hold
      - cancel-other-hold:
          requires:
            - build-on-production
